{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    env: {{ .Values.appEnvironment }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.selector.app }}
    env: {{ .Values.appEnvironment }}
{{- end }}