# Default values for node-app.

# node-app deployment configurations
nodeApp:
  enabled: true

# deployment/service/hpa name
appName: node-app
appEnvironment: "dev"

namespace: "ns-demo"

env:
  NODE_ENV: "dev"
  PORT: "9000"
  HTTP_LOGGING: "true"
  COMPRESSION: "true"

# No need to modify replicaCount if HPA is enabled
replicaCount: 1

#metadata:
#  deploymentName: "backend-api-gateway"

# Rolling Update Configurations
maxSurge: 1
maxUnavailable: 0

containers:
  image:
    pullPolicy: IfNotPresent
    repository: pavanmakadia/node-app
    tag: "demo"
  ports:
    containerPort: 9000
    name: http
    protocol: TCP
  healthChecks:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 8

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

# Service definition
service:
  enabled: true
  port: 80
  targetPort: http
  selector:
    app: node-app

# HPA autoscaling definition
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetRequestPerSecond: "3000m"
  # targetRequestPerSecondMetricName: app_httprequests_transactions_count_avg
  # targetMemoryUtilizationPercentage: 80

# Ingress gateway configurations
ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    # cert-manager.io/cluster-issuer: example-issuer
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_set_headers "X-Frame-Options: SAMEORIGIN";
    #   more_set_headers "X-XSS-Protection: 1; mode=block";
    #   more_set_headers "X-Content-Type-Options: nosniff";
    #   more_set_headers "Content-Security-Policy: default-src 'self' blob: https: data: 'unsafe-inline' 'unsafe-eval' ";
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: app-demo.example.com
  path: /
  #tls:
  #  enabled: true
  #  secretName: proplay-ssl-cert
