#apiVersion: autoscaling/v2beta2
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: node-app
    env: dev
  name: hpa-node-app
  namespace: ns-demo
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pod-node-app
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
#  targetCPUUtilizationPercentage: 80
#  targetMemoryUtilizationPercentage: 80
