apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node-app
  namespace: ns-demo
  labels:
    app: node-app
    env: dev
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
