# ClusterIP service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app
    env: dev
  name: svc-node-app
  namespace: ns-demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: node-app
    env: dev
  type: ClusterIP
